# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
